channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - r-essentials
  - r-base
  - r-vioplot
  - r-corrplot
  - r-gmodels
  - r-matrixstats
  - r-lmperm
  - r-pwr
  - r-fnn
  - r-klar
  - r-dmwr
  - r-xgboost
  - r-ellipse
  - r-mclust
  - r-ca
  - r-ggplot2
  - r-irkernel
  - r-boot
  - r-randomforest
